# Generated by Django 3.2.6 on 2022-01-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='ulr_name',
            new_name='url_name',
        ),
    ]
